### ISSUE TITLE
putwch() argument must be a unicode character, not int

### ISSUE THREAD

**Issue by TylerNakamura** [spediso/redditvotebot#1]
Here is the error message I got after passing in my reddit username:

**Comment by TylerNakamura** [comment]
$ python redditvotebot.py >> output.txt
:0: UserWarning: The keyword `bot` in your user_agent may be problematic.
c:\Users\DCmd\AppData\Local\Programs\Python\Python35\lib\site-packages\praw\decorators.py:77: DeprecationWarning: reddit intends to disable password-based authentication of API clients sometime in the near future. As a result this method will be removed in a future major version of PRAW.

For more information please see:

* Original reddit deprecation notice: https://www.reddit.com/comments/2ujhkr/

* Updated delayed deprecation notice: https://www.reddit.com/comments/37e2mv/

Pass ``disable_warning=True`` to ``login`` to disable this warning.
  warn(msg, DeprecationWarning)
throwthrowdhasaskb
Traceback (most recent call last):
  File "redditvotebot.py", line 8, in <module>
    r.login()
  File "<decorator-gen-51>", line 2, in login
  File "c:\Users\DCmd\AppData\Local\Programs\Python\Python35\lib\site-packages\praw\decorators.py", line 78, in wrap
    return function(*args, **kwargs)
  File "c:\Users\DCmd\AppData\Local\Programs\Python\Python35\lib\site-packages\praw\__init__.py", line 1450, in login
    .encode('ascii', 'ignore'))
  File "c:\Users\DCmd\AppData\Local\Programs\Python\Python35\lib\getpass.py", line 104, in win_getpass
    msvcrt.putwch(c)
TypeError: putwch() argument must be a unicode character, not int

**Comment by TylerNakamura** [comment]
Great work on the simple bot. Thank for writing it

**Comment by spediso** [comment]
TylerNakamura, you can disable to error by simply adding disable_warning=True after your password.  For example:  r.login('username', 'password', disable_warning=True)

I'm not sure if the bot works anymore to be honest.  I haven't messed with it in almost two years.  Maybe I will update it in the near future.

**Comment by TylerNakamura** [comment]
Okay, I was having some other problems with it. I guess I will go ahead and rewrite it at some point. Thanks for answering so quickly!

All the best,
